### ISSUE TITLE
ファイル名の命名規則について

### ISSUE THREAD

**Issue by opamaDX** [tech-is/teamMtoF#5]
ツリー構造について、命名規則を決めます。

# 命名規則

- [ ] login_view
- [ ] view_login
- [ ] login_v
- [ ]  login

**Comment by opamaDX** [comment]
test- 
login_viewがいいです！！！！！

**Comment by opamaDX** [comment]
something_mvc にしときます

**Comment by taic-dev** [comment]
mail機能を作るファイル名は、send_mailにしておきます！！
